<?php
// src/AppBundle/Repository/EmailHolderRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailHolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailHolderRepository extends EntityRepository
{
	public function getEmailHoldersAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.tn', 'ASC' )
		;
		return $qb->getQuery ()->getResult ();
	}
	
	public function getEmailHoldersAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.tn', 'ASC' )
		;
		return $qb;
	}
	
}