<?php
// src/AppBundle/Repository/EvaluationRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends EntityRepository
{
	public function getEvaluationsAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.score', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getEvaluationsAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.score', 'ASC' )
		;
	
		return $qb;
	}
	
	public function getEvaluationByQuizScore($qid=null,$score=0) {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select('e')
		->where('e.quiz = :quiz')
		->andWhere('e.score <= :score')
		->setParameter('quiz', $qid)
		->setParameter ( 'score', $score )
		->addOrderBy ( 'e.score', 'DESC' )
		->setMaxResults( 1 )
		;
	
		return $qb->getQuery ()->getOneOrNullResult();
	}
	
}