<?php
// src/AppBundle/Repository/PlaceHolderRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceHolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceHolderRepository extends EntityRepository
{
	public function getPlaceHoldersAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.ph', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getPlaceHoldersAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.ph', 'ASC' )
		;
	
		return $qb;
	}
	
}