<?php
// src/AppBundle/Repository/QuestionRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function getQuestionsAll()
    {

        $qb = $this->createQueryBuilder('e')
            ->select('e')
            ->addOrderBy('e.title', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getQuestionsAllQB()
    {

        $qb = $this->createQueryBuilder('e')
            ->select('e')
            ->addOrderBy('e.title', 'ASC')
        ;

        return $qb;
    }

    public function getQuestionsStatusCount($status = '1')
    {

        $qb = $this->createQueryBuilder('e')
            ->select('COUNT(e)')
            ->where('e.status = :status')
            ->setParameter('status', $status);

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Gibt die Query zum laden aller Entities zurück
     *
     *return \Doctrine\ORM\Query Die Query
     */
    public function getFindAllQuery()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->getEntityName(), 'e')
            ->getQuery();
        return $query;
    }
}
