<?php
// src/AppBundle/Repository/ScreenGameoverRepository.php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScreenGameoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenGameoverRepository extends EntityRepository
{
	public function getScreenGameoversAll() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb->getQuery ()->getResult ();
	}
	
	public function getScreenGameoversAllQB() {
	
		$qb = $this->createQueryBuilder ( 'e' )
		->select ( 'e' )
		->addOrderBy ( 'e.title', 'ASC' )
		;
	
		return $qb;
	}
	
	
}